### ISSUE TITLE
Questions to enhance usage

### ISSUE THREAD

**Issue by rphlmr** [mitchelvanbever/remix-auth-supabase-strategy#4]
Hi 👋

Thank you for this strategy 👍 

Do you think it's possible to enhance the usage of checkSession, so, we don't need to pass again and again : `sessionStorage`, `sessionKey` and `sessionErrorKey` ?

I think of something like that: 

```js
export const supabaseStrategy = new SupabaseStrategy(
  {
    supabaseUrl,
    supabaseOptions,
    supabaseKey: supabaseAnonKey,
    sessionStorage,
    authenticateOptions
  },
  // simple verify example for email/password auth
  ({ form }) => {
   ...
    })
  },
)
...
 async checkSession(req: Request,  options: AuthenticateOptions) {
    const cookie = await this.extractSession(req) // internally use this.sessionStorage 

    if (!cookie?.[this.authenticateOptions.sessionKey]?.refresh_token || !cookie?.[this.authenticateOptions.sessionKey]?.access_token)
      return this.handleResult(req,  { ...this.authenticateOptions, ...options }, 'No session data found', true) // internally use this.sessionStorage 

    const session = await this.getUser(cookie?.[this.authenticateOptions.sessionKey]?.access_token)

    if (!session || session?.error) {
      const [res, error] = await handlePromise(this.handleRefreshToken(cookie?.[this.authenticateOptions.sessionKey]?.refresh_token))

      if (!res?.data || res?.error || error)
        return this.handleResult(req, { ...this.authenticateOptions, ...options }, 'Could not refresh session', true) 

      // flash new data
      return this.success(res.data, req, this.sessionStorage { ...this.authenticateOptions, successRedirect: options?.successRedirect ?? '/' }) // or create a this.handleSuccess ? 
    }

    if (!session)
      return this.handleResult(req, { ...this.authenticateOptions, ...options }, 'No session data found', true)

    return this.handleResult(req, { ...this.authenticateOptions, ...options }, { ...cookie?.[this.authenticateOptions?.sessionKey], ...session?.user }, false)
  }
```

That's just an idea. With this snippet we can override AuthenticateOptions on needs.
But, maybe I should just make a curry function if this enhancement only feat my needs 😅

```js
export const checkSession = ( req: Request, options: Partial<AuthenticateOptions> = {}) =>
  supabaseStrategy.checkSession(request, sessionStorage, {
    sessionKey: "sb:session",
    sessionErrorKey: "sb:error",
    ...options
  });
```

**Comment by mitchelvanbever** [comment]
Hi thanks for raising this issue. 

I've been working the last couple of days on giving more freedom to the user (to allow for various strategies). But I know that there are some things on my list already for improving the current implementation of `checkSession`.

I think your suggestion would indeed make a lot of sense! 

I'll probably have some time to implement it tomorrow but also open to a PR if that's something you would be interested in doing 🙁

**Comment by rphlmr** [comment]
Hi thanks for your feedback.

I think I could try to make a pull request if you are busy, even if I don't know anything about vite  :D 
I try to pull the project but, maybe It's me, my prettier plugin (vscode) rewrites all the files 🤯.
Do you advise to disabled it (I see format on save off on the repo .vscode folder) ? 

PS : I don't want to undermine your plans ;)

**Comment by mitchelvanbever** [comment]
> Hi thanks for your feedback.
> 
> I think I could try to make a pull request if you are busy, even if I don't know anything about vite :D I try to pull the project but, maybe It's me, my prettier plugin (vscode) rewrites all the files 🤯. Do you advise to disabled it (I see format on save off on the repo .vscode folder) ?
> 
> PS : I don't want to undermine your plans ;)

PR's are welcome :) I'm currently busy with a lot of things and the refactoring of checkSession isn't high on that list.

Easiest would be if you'd fork the repo, branch off main and create a PR from your fork to my repo.

Linting on the repo is still experimental (as I'm playing around with https://github.com/antfu/eslint-config). I've just pushed a refactor to main to include the formatOnSave in vscode settings (and yeah prettier is disabled a.t.m so that's probably what is messing it up 😁)

**Comment by rphlmr** [comment]
Now closed, thank you @mitchelvanbever  for helping me :)
